import GlobalStyle from "@/libs/global-styles";
import StyledComponentsRegistry from "@/libs/ssc-reg";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Content, MainLayout } from "./layout.styled";
import { Theme } from "@radix-ui/themes";
import NavBar from "@/components/NavBar";
import AuthProvider from "@/providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Хакатон",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <GlobalStyle />

        <body className={inter.className}>
          <AuthProvider>
            <Theme key={"asdasd"}>
              <MainLayout>
                <NavBar />

                <Content>{children}</Content>
              </MainLayout>
            </Theme>
          </AuthProvider>
        </body>
      </StyledComponentsRegistry>
    </html>
  );
}
